### ISSUE TITLE
Global installed phantomjs

### ISSUE THREAD

**Issue by jifeon** [twolfson/phantomjssmith#10] opened 2015-07-09 11:49 UTC
Why does it require phantomjs to be installed globally? Maybe need to add phantom to dependencies and use local version?

**Comment by twolfson** [comment] 2015-07-09 16:54
The README links to how to use a local installation. This is also a duplicate of #4 and #9. #4 has the easiest set of instructions to follow.

**Closed by twolfson** 2015-07-09 16:54 UTC
